import { jsPDF } from 'jspdf';
import { generateCitation } from './citationGenerator';

/**
 * Export a single paper's citation as a formatted PDF document
 */
export function exportSingleCitationPdf(resource, selectedStyle = 'APA') {
  if (!resource) return;
  const doc = new jsPDF();
  const citationText = generateCitation(resource, selectedStyle);

  // Top Header Banner
  doc.setFillColor(16, 185, 129); // Emerald accent
  doc.rect(0, 0, 210, 26, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(15);
  doc.setFont('helvetica', 'bold');
  doc.text('ResearchVault — Academic Citation Report', 14, 17);

  // Document Metadata
  doc.setTextColor(15, 23, 42);
  doc.setFontSize(13);
  doc.setFont('helvetica', 'bold');
  const splitTitle = doc.splitTextToSize(resource.title || 'Untitled Research Paper', 180);
  doc.text(splitTitle, 14, 38);

  let currentY = 38 + (splitTitle.length * 6);

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 116, 139);
  doc.text(`Authors: ${resource.authors || 'Scholarly Author'}`, 14, currentY);
  currentY += 5;
  doc.text(`Publication Year: ${resource.publicationYear || 'N/A'} • Journal/Venue: ${resource.journal || 'Academic Repository'}`, 14, currentY);
  currentY += 5;
  doc.text(`Category: ${resource.category || 'Research'}`, 14, currentY);
  currentY += 12;

  // Formatted Citation Box
  doc.setFillColor(248, 250, 252);
  doc.setDrawColor(226, 232, 240);
  doc.roundedRect(14, currentY, 182, 36, 3, 3, 'FD');

  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(16, 185, 129);
  doc.text(`Formatted Citation Reference (${selectedStyle} Standard):`, 18, currentY + 10);

  doc.setFontSize(9.5);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(15, 23, 42);
  const splitCitation = doc.splitTextToSize(citationText, 174);
  doc.text(splitCitation, 18, currentY + 20);

  currentY += 46;

  // DOI / Source Link
  const link = resource.sourceUrl || resource.downloadUrl || (resource.doi ? `https://doi.org/${resource.doi}` : '');
  if (link) {
    doc.setFontSize(8.5);
    doc.setTextColor(59, 130, 246);
    doc.text(`Official Document URL / DOI: ${link}`, 14, currentY);
    currentY += 12;
  }

  // Summary Abstract
  if (resource.abstractText && resource.abstractText.length > 20) {
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(15, 23, 42);
    doc.text('Summary Abstract:', 14, currentY);
    currentY += 6;

    doc.setFontSize(8.5);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(71, 85, 105);
    const cleanAbstract = resource.abstractText.slice(0, 600) + (resource.abstractText.length > 600 ? '...' : '');
    const splitAbstract = doc.splitTextToSize(cleanAbstract, 180);
    doc.text(splitAbstract, 14, currentY);
  }

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(148, 163, 184);
  doc.text(`Generated by ResearchVault Digital Library • ${new Date().toLocaleDateString()}`, 14, 285);

  const cleanFileName = (resource.title || 'Citation').replace(/[^a-zA-Z0-9]/g, '_').slice(0, 30);
  doc.save(`${cleanFileName}_${selectedStyle}_Citation.pdf`);
}

/**
 * Export a library collection of citations as a formatted PDF catalog
 */
export function exportLibraryCitationsPdf(resources = [], selectedStyle = 'APA') {
  if (!resources || resources.length === 0) return;
  const doc = new jsPDF();

  // Top Header Banner
  doc.setFillColor(16, 185, 129);
  doc.rect(0, 0, 210, 26, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(15);
  doc.setFont('helvetica', 'bold');
  doc.text('ResearchVault — Literature Citation Catalog', 14, 17);

  doc.setFontSize(9);
  doc.text(`Total Records: ${resources.length} • Format: ${selectedStyle}`, 145, 17);

  let currentY = 36;

  resources.forEach((r, idx) => {
    if (currentY > 260) {
      doc.addPage();
      currentY = 22;
    }

    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(15, 23, 42);
    const entryHeader = `${idx + 1}. ${r.title || 'Untitled Research Paper'}`;
    const splitTitle = doc.splitTextToSize(entryHeader, 180);
    doc.text(splitTitle, 14, currentY);
    currentY += splitTitle.length * 5;

    const citationText = generateCitation(r, selectedStyle);
    doc.setFontSize(8.5);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(51, 65, 85);
    const splitCitation = doc.splitTextToSize(citationText, 174);
    doc.text(splitCitation, 18, currentY);
    currentY += splitCitation.length * 4.5 + 8;
  });

  // Footer on last page
  doc.setFontSize(8);
  doc.setTextColor(148, 163, 184);
  doc.text(`Generated by ResearchVault Digital Library • ${new Date().toLocaleDateString()}`, 14, 285);

  doc.save(`ResearchVault_Citations_Catalog_${Date.now()}.pdf`);
}
