import { jsPDF } from "jspdf";

const PAGE_MARGIN = 48;
const LINE_HEIGHT = 16;
const FONT_BODY = 11;
const FONT_H1 = 18;
const FONT_H2 = 14;

/**
 * Exports literature review text (or any AI-generated Markdown-style
 * text) to a downloadable PDF file.
 *
 * @param {string} reviewText - The AI-generated review content.
 * @param {string} documentTitle - Title shown at the top of the PDF and used as the filename.
 */
export function exportReviewToPdf(reviewText, documentTitle = "Literature Review") {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const usableWidth = pageWidth - PAGE_MARGIN * 2;

  let cursorY = PAGE_MARGIN;

  const ensureSpace = (neededHeight) => {
    if (cursorY + neededHeight > pageHeight - PAGE_MARGIN) {
      doc.addPage();
      cursorY = PAGE_MARGIN;
    }
  };

  const writeWrappedText = (text, fontSize, isBold = false) => {
    doc.setFont("helvetica", isBold ? "bold" : "normal");
    doc.setFontSize(fontSize);
    const lines = doc.splitTextToSize(text, usableWidth);
    lines.forEach((line) => {
      ensureSpace(LINE_HEIGHT);
      doc.text(line, PAGE_MARGIN, cursorY);
      cursorY += LINE_HEIGHT;
    });
  };

  // Title
  doc.setFont("helvetica", "bold");
  doc.setFontSize(FONT_H1 + 2);
  const titleLines = doc.splitTextToSize(documentTitle, usableWidth);
  titleLines.forEach((line) => {
    ensureSpace(LINE_HEIGHT + 4);
    doc.text(line, PAGE_MARGIN, cursorY);
    cursorY += LINE_HEIGHT + 4;
  });
  cursorY += 8;

  doc.setDrawColor(200);
  doc.line(PAGE_MARGIN, cursorY, pageWidth - PAGE_MARGIN, cursorY);
  cursorY += 20;

  // Parse and render line by line
  const rawLines = String(reviewText || "").split("\n");

  rawLines.forEach((rawLine) => {
    const line = rawLine.trimEnd();

    if (!line.trim()) {
      cursorY += LINE_HEIGHT / 2;
      return;
    }

    if (line.startsWith("# ")) {
      cursorY += 10;
      ensureSpace(FONT_H1 + LINE_HEIGHT);
      writeWrappedText(line.replace(/^#\s+/, ""), FONT_H1, true);
      cursorY += 6;
      return;
    }

    if (line.startsWith("## ")) {
      cursorY += 8;
      ensureSpace(FONT_H2 + LINE_HEIGHT);
      writeWrappedText(line.replace(/^##\s+/, ""), FONT_H2, true);
      cursorY += 4;
      return;
    }

    if (line.startsWith("- ") || line.startsWith("* ")) {
      const bulletText = "•  " + line.replace(/^[-*]\s+/, "");
      writeWrappedText(bulletText, FONT_BODY, false);
      return;
    }

    // Strip markdown bold markers (**text**) since jsPDF doesn't render
    // inline formatting — keep the plain text instead.
    const plain = line.replace(/\*\*(.+?)\*\*/g, "$1");
    writeWrappedText(plain, FONT_BODY, false);
  });

  // Footer with page numbers
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(150);
    doc.text(
      `Page ${i} of ${pageCount} — Generated by ResearchVault AI`,
      pageWidth / 2,
      pageHeight - 20,
      { align: "center" }
    );
  }

  const safeFilename = documentTitle
    .replace(/[^a-z0-9\s-]/gi, "")
    .trim()
    .replace(/\s+/g, "_")
    .slice(0, 80) || "literature_review";

  doc.save(`${safeFilename}.pdf`);
}
